### ISSUE TITLE
Github set-output deprecation notice

### ISSUE THREAD

**Issue by TomerFi** [TomerFi/version-bumper#94]
### What did you have in mind?

`set-output` is deprecated:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

We use it in [.github/workflows/pr.yml](https://github.com/TomerFi/version-bumper/blob/dev/.github/workflows/pr.yml), in [.github/workflows/release.yml](https://github.com/TomerFi/version-bumper/blob/dev/.github/workflows/release.yml), and in [.github/workflows/stage.yml](https://github.com/TomerFi/version-bumper/blob/dev/.github/workflows/stage.yml).

### Are you trying to fix a problem?

Prepare for deprecation by GitHub.

### Any lead on how this feature may be implemented?

Using [environment files](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files).

**Comment by AlexNDRmac** [comment]
Hi @TomerFi, I would like to help you with this.

**Comment by TomerFi** [comment]
Very much appreciated, thank you very much.
